# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

################################################################################################################################################
# Fortify Application Security provides your team with solutions to empower DevSecOps practices, enable cloud transformation, and secure your  #
# software supply chain. To learn more about Fortify, start a free trial or contact our sales team, visit fortify.com.                         #
#                                                                                                                                              #
# Use this starter workflow as a basis for integrating Fortify Application Security Testing into your GitHub workflows. This template          #
# demonstrates the steps to package the code+dependencies, initiate a scan, and optionally import SAST vulnerabilities into GitHub Security    #
# Code Scanning Alerts. Additional information is available in the workflow comments and the Fortify AST Action / fcli / Fortify product       #
# documentation. If you need additional assistance, please contact Fortify support.                                                            #
################################################################################################################################################

name: GSA Fortify Scan

# Customize trigger events based on your DevSecOps process and/or policy
on:
 # push:
 #   branches: [ "main" ]
 # pull_request:
    # The branches below must be a subset of the branches above
 #   branches: [ "main" ]
 # schedule:
 #   - cron: '28 23 * * 6'
  workflow_dispatch:
  
  workflow_call:
   inputs:
    PACKAGE_EXTRA_OPTS:
     type: string
     required: false
     default: ''
     description: extra package options like excludes for the scanner
    ASSESSMENT_TYPE:
      type: string
      required: false
      default: "Static+"
      description: the type of assessment
    COPY_FROM_RELEASE:
      type: string
      required: false
      default: ""
   secrets:
       FOD_CLIENT_ID:
         required: true
       FOD_CLIENT_SECRET:
         required: true
       HTTP_PROXY:
        required: false
       HTTPS_PROXY:
        required: false

jobs:
  Fortify-AST-Scan:
    # Use the appropriate runner for building your source code. Ensure dev tools required to build your code are present and configured appropriately (MSBuild, Python, etc).
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v4

      # Java is required to run the various Fortify utilities. Ensuring proper version is installed on the runner.
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      # Perform SAST and optionally SCA scan via Fortify on Demand/Fortify Hosted/Software Security Center, then
      # optionally export SAST results to the GitHub code scanning dashboard. In case further customization is
      # required, you can use sub-actions like fortify/github-action/setup@v1 to set up the various Fortify tools
      # and run them directly from within your pipeline; see https://github.com/fortify/github-action#readme for
      # details.
      - name: Run FoD SAST Scan
        uses: fortify/github-action@v1.7
        with:
          sast-scan: true
        env:
          #### TODO: remove FOD_RELEASE and pass from caller as Github var,  FOD_RELEASE: tlegette-gsa/IWA-Java-v1.0:main ####
          #### REMOVE: for now force to test app in GSAH #####
          #### FOD_RELEASE: 21473

          ### Proxy settings (optional)
          http_proxy: ${{secrets.HTTP_PROXY}}
          https_proxy: ${{secrets.HTTPS_PROXY}}
          
          ### Required configuration when integrating with Fortify on Demand
          FOD_URL: https://fed.fortifygov.com
          FOD_CLIENT_ID: ${{secrets.FOD_CLIENT_ID}}
          FOD_CLIENT_SECRET: ${{secrets.FOD_CLIENT_SECRET}}
          #DO_SETUP: true
          #SETUP_EXTRA_OPTS: --assessment-type "${{inputs.ASSESSMENT_TYPE}}" ${{ inputs.COPY_FROM_RELEASE != '' && format('--copy-from "{0}"', inputs.COPY_FROM_RELEASE) || '' }}
          #DO_PACKAGE_DEBUG: true 
          ### Optional configuration when integrating with Fortify on Demand
          PACKAGE_EXTRA_OPTS: ${{inputs.PACKAGE_EXTRA_OPTS}}                       # Extra 'scancentral package' options, like '-oss'' if
                                                           # Debricked SCA scan is enabled on Fortify on Demand
          # EXTRA_FOD_LOGIN_OPTS: --socket-timeout=60s     # Extra 'fcli fod session login' options
          FOD_RELEASE: "GSA/ise-appsec:nodejs_test"                  # FoD release name, default: <org>/<repo>:<branch>; may
                                                           # replace app+release name with numeric release ID
          # DO_WAIT: true                                  # Wait for scan completion, implied if 'DO_EXPORT: true'
          DO_EXPORT: true                                # Export SAST results to GitHub code scanning dashboard
